# @package model.head
name: FastaiHead
init_args:
  num_classes: ${model.num_classes}
  act: ReLU
  lin_ftrs: null
  ps: 0.5
  concat_pool: true
  first_bn: true
  bn_final: false
  lr: 1e-03
  wd: 0.
  filter_wd: true
