# @package model.backbone
name: ResNetBackbone
init_args:
  model_name: null
  act: null
  lr: null
  wd: null
  lr_div: 10
  freeze_at: 2
  pretrained: true
  drop_block_rate: null
  drop_path_rate: null
  bn_tf: false
