# -----------------------------------------------------------------------------
# Generic Config definition for Image Classification
# -----------------------------------------------------------------------------

# ---------------------------------------------------------------------------- #
# Hydra defaults list
# ---------------------------------------------------------------------------- #
# loads default configs
defaults:
  - /loss@training.loss_fn: /classification/soft_target_ce
  - /model@_group_: /classification/general_cnn
  - /backbone@model.backbone: /classification/resnet_cls
  - /head@model.head: /classification/fastai_head
  - optimizer: adamw
  - scheduler: onecycle

# -----------------------------------------------------------------------------
# Dataset
# -----------------------------------------------------------------------------
datasets:
  train: " "
  valid: " "
  test: null

# -----------------------------------------------------------------------------
# DataLoader
# -----------------------------------------------------------------------------
dataloader:
  train:
    num_workers: 0
    batch_size: 32
    shuffle: False
    pin_memory: false
    sampler: null
    collate_fn: null

  valid: ${dataloader.train}
  test: ${dataloader.train}

# -----------------------------------------------------------------------------
# INPUT
# -----------------------------------------------------------------------------
input:
  channels: 3
  height: 224
  width: 224

# -----------------------------------------------------------------------------
# MODEL definitions: Load using hydra defaults list
# -----------------------------------------------------------------------------
model:
  num_classes: 10

# -----------------------------------------------------------------------------
# OPTIMATION
# -----------------------------------------------------------------------------
# Note: values that are -1 are computed at runtime to explicitely set them set them to something other that -1
optimization:
  # Additional Parameters for optimization
  # # total number of steps per epochs, this value is computed at runtime and mandatory to have.
  steps_per_epoch: -1
  # total number of training steps, computed at runtime or explicitly set here; mandatory to have
  max_steps: -1
  # total number of training epochs, computed at runtime or explicitly set here; mandatory to have.
  max_epochs: -1

# -----------------------------------------------------------------------------
# Hydra Options
# -----------------------------------------------------------------------------
hydra:
  job_logging:
    root:
      handlers: null
