# -----------------------------------------------------------------------------
# Generic Config definition for Image Classification
# -----------------------------------------------------------------------------

# ---------------------------------------------------------------------------- #
# Hydra defaults list
# ---------------------------------------------------------------------------- #
# loads default configs
defaults:
  - /loss@training.train_loss_fn: /classification/soft_target_ce
  - /loss@training.eval_loss_fn: /classification/ce_loss
  - /model@_group_: /classification/general_cnn
  - /backbone@model.backbone: /classification/resnet_cls
  - /head@model.head: /classification/fastai_head
  - optimizer: adamw
  - scheduler: onecycle

# -----------------------------------------------------------------------------
# Dataset
# -----------------------------------------------------------------------------
datasets:
  train: " "
  valid: " "
  test: null

# -----------------------------------------------------------------------------
# DataLoader
# -----------------------------------------------------------------------------
dataloader:
  batch_size: 32
  pin_memory: false
  num_workers: 0
  train:
    num_workers: ${dataloader.num_workers}
    batch_size: ${dataloader.batch_size}
    pin_memory: ${dataloader.pin_memory}
    shuffle: true
    sampler: null
    collate_fn: null
  valid:
    num_workers: ${dataloader.num_workers}
    batch_size: ${dataloader.batch_size}
    pin_memory: ${dataloader.pin_memory}
    shuffle: false
    sampler: null
    collate_fn: null
  test:
    num_workers: ${dataloader.num_workers}
    batch_size: ${dataloader.batch_size}
    pin_memory: ${dataloader.pin_memory}
    shuffle: true
    sampler: null
    collate_fn: null

# -----------------------------------------------------------------------------
# INPUT
# -----------------------------------------------------------------------------
input:
  channels: 3
  height: 224
  width: 224
  # mean, and std for normalization gale provides automatic values
  # for imagenet, cifar and mnist
  mean: imagenet
  std: imagenet

# @TODO: Add augmix support
training:
  # Apply mixup to the Inputs/CutMix
  mixup:
    # Turns off mixup after this epoch
    off_epoch: false
    init_args:
      # mixup alpha value, mixup is active if > 0.
      mixup_alpha: 0.4
      # cutmix alpha value, cutmix is active if > 0.
      cutmix_alpha: 1.0
      # cutmix is active and uses this vs alpha if not None.
      cutmix_minmax: null
      # probability of applying mixup or cutmix per batch or element
      prob: 0.0
      # probability of switching to cutmix instead of mixup when both are active
      switch_prob: 0.5
      mode: batch
      correct_lam: true
      # label smoothing factor to apply
      label_smoothing: 0.0
      num_classes: ${model.num_classes}

# -----------------------------------------------------------------------------
# MODEL definitions: Load using hydra defaults list
# -----------------------------------------------------------------------------
model:
  num_classes: 10

# -----------------------------------------------------------------------------
# OPTIMATION
# -----------------------------------------------------------------------------
# Note: values that are -1 are computed at runtime to explicitely set them set them to something other that -1
optimization:
  # Additional Parameters for optimization
  # # total number of steps per epochs, this value is computed at runtime and mandatory to have.
  steps_per_epoch: -1
  # total number of training steps, computed at runtime or explicitly set here; mandatory to have
  max_steps: -1
  # total number of training epochs, computed at runtime or explicitly set here; mandatory to have.
  max_epochs: -1

# -----------------------------------------------------------------------------
# Hydra Options
# -----------------------------------------------------------------------------
hydra:
  job_logging:
    root:
      handlers: null
