# @package optimization.optimizer
name: RangerGC
init_args:
  lr: 1e-3
  betas: [0.95, 0.999]
  eps: 1e-05
  k: 6
  N_sma_threshhold: 5
  aplha: 0.5
  weight_decay: 0
  use_gc: true
  gc_conv_only: true