# @package MODEL.BACKBONE
name: TimmBackboneBase
init_args:
  model_name: ???
  act: null
  lr: ${TRAINING.backbone_lr}
  wd: ${TRAINING.backbone_wd}
  freeze_bn: false
  freeze_at: false
  filter_wd: false
  pretrained: true
  drop_block_rate: null
  drop_path_rate: null
  bn_tf: false
