name: TimmBackboneBase
init_args:
  model_name: ???
  act: null
  lr: null
  wd: null
  freeze_bn: false
  freeze_at: false
  filter_wd: false
  pretrained: true
  drop_block_rate: null
  drop_path_rate: null
  bn_tf: false
