# @package model.backbone
name: ResNetBackbone
init_args:
  model_name: resnet18
  act: null
  lr: 2e-03
  wd: 1e-02
  lr_div: 10
  freeze_at: 2
  pretrained: true
  drop_block_rate: null
  drop_path_rate: null
  bn_tf: false
