# @package model.backbone
name: TimmBackboneBase
init_args:
  model_name: efficientnet_b0
  act: null
  lr: 1e-03
  wd: 0.
  freeze_bn: false
  freeze_at: false
  filter_wd: false
  pretrained: true
  drop_block_rate: null
  drop_path_rate: null
  bn_tf: false
